assert_lefthook_installed: true
colors: false
no_tty: true
skip_output: meta,execution,execution_out,execution_info
pre-commit:
  parallel: true
  commands:
    lint:
      run: make lint
      stage_fixed: true
    format:
      run: test -z "$(go run mvdan.cc/gofumpt@latest -d -e . | tee /dev/stderr)" && make format
      stage_fixed: true
    audit:
      run: make audit
    test:
      run: make test
